version: "3.9"

services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    rocketstats_backend:
        build: .
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_HOST: mongodb
        ports:
            - "8080:8080"
        depends_on:
            - mongodb

volumes:
    mongodb_data:
