version: "3.9"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U myuser" ]
            interval: 10s
            timeout: 5s
            retries: 5

    rocketstats_backend:
        build: .
        environment:
            RUST_LOG: info
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
